vich_uploader:
    db_driver: orm

    mappings:
        excursion_image:
            uri_prefix: /photos/excursions
            upload_destination: '%kernel.project_dir%/public/photos/excursions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
